# Generated by Django 3.2.5 on 2021-07-20 16:56

import django.contrib.auth.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, default=None, max_length=254, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('NONE', 'None'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='NONE', max_length=255)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('avatar', models.TextField(blank=True, default=None, null=True)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('modified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_by', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
